// builtin/personal 目录路径解析与 CDN 刷新入口(环境变量)
// source: zcode-unpacked/resources/glm/zcode.cjs (14,796,911 bytes, 3.14.1)
// window: bytes 1065900..1067500
// symbols: IV ZCODE_BUILTIN_PROVIDER_CONFIG_FILE, lXe ZCODE_BUILTIN_PROVIDER_BUNDLED_CONFIG_FILE, Hee ZCODE_PERSONAL_PROVIDER_CONFIG_FILE, FZi prepareCliProviderRuntimeEnv, QAe refresh reporter
// NOTE: raw minified code, single line preserved as-is; annotate locally.

;function cfr(e){let t=e[IV]?.trim(),n=e[Hee]?.trim();if(!t&&!n)return null;if(!t||!n)throw new Error("ZCode Built-in \u4E0E Personal Provider Config \u8DEF\u5F84\u5FC5\u987B\u540C\u65F6\u63D0\u4F9B");return Object.freeze({zcodeBuiltinFilePath:t,personalFilePath:n})}var IV,lXe,Hee,uXe,lfr=Y(()=>{"use strict";IV="ZCODE_BUILTIN_PROVIDER_CONFIG_FILE",lXe="ZCODE_BUILTIN_PROVIDER_BUNDLED_CONFIG_FILE",Hee="ZCODE_PERSONAL_PROVIDER_CONFIG_FILE",uXe="provider_config.json";r(cfr,"resolveNodeProviderRuntimePaths")});var efe=Y(()=>{"use strict";OKe();XEe();htr();MKe();Gqt();Kqt();Itr();Ctr();Qqt();Yqt();eWt();Rtr();afr();lfr()});var ffr={};Ng(ffr,{SEA_ZCODE_BUILTIN_PROVIDER_CONFIG_ASSET_KEY:()=>pfr,createCliProviderRefreshReporter:()=>QAe,prepareCliProviderRuntimeEnv:()=>FZi});function QAe(e=process.stderr){return{onBuiltinRefreshError(t){e.write(`ZCode Built-in \u5237\u65B0\u5931\u8D25: ${t instanceof Error?t.message:"unknown error"}
`)},onBuiltinRefreshResult(t){(t.result==="updated"||process.env.NODE_ENV!=="production")&&e.write(`ZCode Built-in ${t.result}${t.reason?` (${t.reason})`:""}${t.revision===void 0?"":` revision=${t.revision} source=CDN`}
`)}}}async function FZi(e){if(!jZi(e.argv))return{};let t=e.env[IV]?.trim(),n=e.env[Hee]?.trim(),o=e.dataBaseDir??e.env.ZCODE_DATA_BASE_DIR?.trim()??(0,dfr.homedir)();if(t&&n)return{[IV]:t,[Hee]:n};let s=t??await BZi({dataBaseDir:o,entrypoint:e.entrypoint??process.argv[1],sea:e.sea??UZi()}),a=n??(0,qj.join)(o,".zcode","v2",uXe),l=e.appVersion??LL,u=e.platform??LKe(),f=c1(e.env),g=FKe({environmentConfigRoot:(0,qj.join)(o,".zcode","v2"),plat
